// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlq9-l2ADIpGHefqCITWc_ah9FJ68BhmA',
    appId: '1:262662478426:web:02f027526946d722d29663',
    messagingSenderId: '262662478426',
    projectId: 'kalsh-2bafe',
    authDomain: 'kalsh-2bafe.firebaseapp.com',
    storageBucket: 'kalsh-2bafe.firebasestorage.app',
    measurementId: 'G-0S7VPCQJ9S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5pYh4MhtlZL9MGhpqk56rk4VvajUv-P8',
    appId: '1:262662478426:android:51582d8bd3a9fd0dd29663',
    messagingSenderId: '262662478426',
    projectId: 'kalsh-2bafe',
    storageBucket: 'kalsh-2bafe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAufrwP5p6RrJq0s2W0TAd7Uvs01wwjdco',
    appId: '1:262662478426:ios:d851c74fd5aaae3dd29663',
    messagingSenderId: '262662478426',
    projectId: 'kalsh-2bafe',
    storageBucket: 'kalsh-2bafe.firebasestorage.app',
    iosBundleId: 'com.mobisoftseo.kals360',
  );
}
