// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'user_profile_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$UserProfileResponseImpl _$$UserProfileResponseImplFromJson(
  Map<String, dynamic> json,
) => _$UserProfileResponseImpl(
  status: (json['status'] as num).toInt(),
  msg: json['msg'] as String,
  data: UserProfileModel.fromJson(json['data'] as Map<String, dynamic>),
);

Map<String, dynamic> _$$UserProfileResponseImplToJson(
  _$UserProfileResponseImpl instance,
) => <String, dynamic>{
  'status': instance.status,
  'msg': instance.msg,
  'data': instance.data,
};

_$UserProfileModelImpl _$$UserProfileModelImplFromJson(
  Map<String, dynamic> json,
) => _$UserProfileModelImpl(
  id: json['id'] as String?,
  fullName: json['full_name'] as String?,
  mobile: json['mobile'] as String?,
  email: json['email'] as String?,
  dob: json['dob'] as String?,
  photo: json['photo'] as String?,
  bloodGroup: json['blood_group'] as String?,
  maritalStatus: json['marital_status'] as String?,
  religion: json['religion'] as String?,
  nationality: json['nationality'] as String?,
  fatherName: json['father_name'] as String?,
  emergencyName: json['emergency_name'] as String?,
  emergencyContact: json['emergency_contact'] as String?,
  physicalDisability: json['physical_disability'] as String?,
  tShirtSize: json['t_shirt_size'] as String?,
  password: json['password'] as String?,
  trouserSize: json['trouser_size'] as String?,
  experienceStatus: json['experience_status'] as String?,
  totalExperienceYear: json['total_experience_year'] as String?,
  totalExperienceMonth: json['total_experience_month'] as String?,
  currentlyEmployed: json['currently_employed'] as String?,
  applicationStatus: json['application_status'] as String?,
  companyName: json['company_name'] as String?,
  hrmsEmployeeCode: json['hrms_employee_code'] as String?,
  employeeContactNumber: json['employee_contact_number'] as String?,
  vendorEmployeeCode: json['vendor_employee_code'] as String?,
  vendorName: json['vendor_name'] as String?,
  doj: json['doj'] as String?,
  department: json['department'] as String?,
  storeCode: json['store_code'] as String?,
  storeLocation: json['store_location'] as String?,
  storeCity: json['store_city'] as String?,
  designation: json['designation'] as String?,
  managerEmail: json['manager_email'] as String?,
  gender: json['gender'] as String?,
  skillSet: json['skill_set'] as String?,
  state: json['state'] as String?,
  separationDate: json['separation_date'] as String?,
  lastWorkingDate: json['last_working_date'] as String?,
  separationType: json['separation_type'] as String?,
  olGenerate: json['ol_generate'] as String?,
  olGenerateDate: json['ol_generate_date'] as String?,
  sendOlLetter: json['send_ol_letter'] as String?,
  status: json['status'] as String?,
  addedOn: json['added_on'] as String?,
  updatedOn: json['updated_on'] as String?,
  attendance: json['attendance'] as bool? ?? false,
  attendType: json['attend_type'] as String?,
);

Map<String, dynamic> _$$UserProfileModelImplToJson(
  _$UserProfileModelImpl instance,
) => <String, dynamic>{
  'id': instance.id,
  'full_name': instance.fullName,
  'mobile': instance.mobile,
  'email': instance.email,
  'dob': instance.dob,
  'photo': instance.photo,
  'blood_group': instance.bloodGroup,
  'marital_status': instance.maritalStatus,
  'religion': instance.religion,
  'nationality': instance.nationality,
  'father_name': instance.fatherName,
  'emergency_name': instance.emergencyName,
  'emergency_contact': instance.emergencyContact,
  'physical_disability': instance.physicalDisability,
  't_shirt_size': instance.tShirtSize,
  'password': instance.password,
  'trouser_size': instance.trouserSize,
  'experience_status': instance.experienceStatus,
  'total_experience_year': instance.totalExperienceYear,
  'total_experience_month': instance.totalExperienceMonth,
  'currently_employed': instance.currentlyEmployed,
  'application_status': instance.applicationStatus,
  'company_name': instance.companyName,
  'hrms_employee_code': instance.hrmsEmployeeCode,
  'employee_contact_number': instance.employeeContactNumber,
  'vendor_employee_code': instance.vendorEmployeeCode,
  'vendor_name': instance.vendorName,
  'doj': instance.doj,
  'department': instance.department,
  'store_code': instance.storeCode,
  'store_location': instance.storeLocation,
  'store_city': instance.storeCity,
  'designation': instance.designation,
  'manager_email': instance.managerEmail,
  'gender': instance.gender,
  'skill_set': instance.skillSet,
  'state': instance.state,
  'separation_date': instance.separationDate,
  'last_working_date': instance.lastWorkingDate,
  'separation_type': instance.separationType,
  'ol_generate': instance.olGenerate,
  'ol_generate_date': instance.olGenerateDate,
  'send_ol_letter': instance.sendOlLetter,
  'status': instance.status,
  'added_on': instance.addedOn,
  'updated_on': instance.updatedOn,
  'attendance': instance.attendance,
  'attend_type': instance.attendType,
};
